[project]
name = 'Medical-Equipment-Maintenance-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.device-registration]
path = 'contracts/device-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.parts-inventory]
path = 'contracts/parts-inventory.clar'
clarity_version = 2
epoch = 2.5

[contracts.technician-verification]
path = 'contracts/technician-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
